# Generated by Django 4.2.5 on 2023-09-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='receipt_date',
            field=models.DateField(),
        ),
    ]
